//! Request/reply guest module used by the end-to-end test harness.

use anyhow::{Context, Result, anyhow, bail};
use selium_switchboard::Channel;
use selium_userland::entrypoint;
use tracing::info;

/// Flatbuffer bindings generated by the build script.
#[rustfmt::skip]
#[allow(warnings)]
pub mod fbs;

/// Response payload returned to the request/reply client.
pub struct Message {
    /// Echoed payload.
    pub msg: String,
}

#[entrypoint]
async fn request_reply_client(control_channel: i32, reply_channel: i32) -> Result<()> {
    let control_channel = channel_from_arg(control_channel)?;
    let reply_channel = channel_from_arg(reply_channel)?;
    let mut control_reader = control_channel.subscribe(32 * 1024).await?;
    match control_reader
        .read_next()
        .await
        .context("read control signal")?
    {
        Some(_) => {}
        None => bail!("control channel closed before signal"),
    }

    info!("received control signal");
    publish_reply(&reply_channel, "pong").await?;

    Ok(())
}

#[entrypoint]
async fn request_reply_server() -> Result<()> {
    info!("request_reply_server started");
    Ok(())
}

fn channel_from_arg(handle: i32) -> Result<Channel> {
    let handle = u64::try_from(handle).map_err(|_| anyhow!("channel handle is negative"))?;
    // SAFETY: the runtime passes queue shared ids for request/reply channels.
    Ok(unsafe { Channel::from_raw(handle) })
}

async fn publish_reply(channel: &Channel, reply_msg: &str) -> Result<()> {
    let mut publisher = channel.publish().await?;
    publisher.send(reply_msg.as_bytes()).await?;
    publisher.close().await?;
    Ok(())
}
