// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum AdoptRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct AdoptRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for AdoptRequest<'a> {
  type Inner = AdoptRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> AdoptRequest<'a> {
  pub const VT_DIRECTIONS: ::flatbuffers::VOffsetT = 4;
  pub const VT_UPDATES_CHANNEL: ::flatbuffers::VOffsetT = 6;
  pub const VT_CHANNEL: ::flatbuffers::VOffsetT = 8;
  pub const VT_MODE: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    AdoptRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args AdoptRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<AdoptRequest<'bldr>> {
    let mut builder = AdoptRequestBuilder::new(_fbb);
    builder.add_channel(args.channel);
    builder.add_updates_channel(args.updates_channel);
    if let Some(x) = args.directions { builder.add_directions(x); }
    builder.add_mode(args.mode);
    builder.finish()
  }


  #[inline]
  pub fn directions(&self) -> Option<EndpointDirections<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<EndpointDirections>>(AdoptRequest::VT_DIRECTIONS, None)}
  }
  #[inline]
  pub fn updates_channel(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(AdoptRequest::VT_UPDATES_CHANNEL, Some(0)).unwrap()}
  }
  #[inline]
  pub fn channel(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(AdoptRequest::VT_CHANNEL, Some(0)).unwrap()}
  }
  #[inline]
  pub fn mode(&self) -> AdoptMode {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<AdoptMode>(AdoptRequest::VT_MODE, Some(AdoptMode::Alias)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for AdoptRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<EndpointDirections>>("directions", Self::VT_DIRECTIONS, false)?
     .visit_field::<u64>("updates_channel", Self::VT_UPDATES_CHANNEL, false)?
     .visit_field::<u64>("channel", Self::VT_CHANNEL, false)?
     .visit_field::<AdoptMode>("mode", Self::VT_MODE, false)?
     .finish();
    Ok(())
  }
}
pub struct AdoptRequestArgs<'a> {
    pub directions: Option<::flatbuffers::WIPOffset<EndpointDirections<'a>>>,
    pub updates_channel: u64,
    pub channel: u64,
    pub mode: AdoptMode,
}
impl<'a> Default for AdoptRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    AdoptRequestArgs {
      directions: None,
      updates_channel: 0,
      channel: 0,
      mode: AdoptMode::Alias,
    }
  }
}

pub struct AdoptRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> AdoptRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_directions(&mut self, directions: ::flatbuffers::WIPOffset<EndpointDirections<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<EndpointDirections>>(AdoptRequest::VT_DIRECTIONS, directions);
  }
  #[inline]
  pub fn add_updates_channel(&mut self, updates_channel: u64) {
    self.fbb_.push_slot::<u64>(AdoptRequest::VT_UPDATES_CHANNEL, updates_channel, 0);
  }
  #[inline]
  pub fn add_channel(&mut self, channel: u64) {
    self.fbb_.push_slot::<u64>(AdoptRequest::VT_CHANNEL, channel, 0);
  }
  #[inline]
  pub fn add_mode(&mut self, mode: AdoptMode) {
    self.fbb_.push_slot::<AdoptMode>(AdoptRequest::VT_MODE, mode, AdoptMode::Alias);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> AdoptRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    AdoptRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<AdoptRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for AdoptRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("AdoptRequest");
      ds.field("directions", &self.directions());
      ds.field("updates_channel", &self.updates_channel());
      ds.field("channel", &self.channel());
      ds.field("mode", &self.mode());
      ds.finish()
  }
}
