// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ABI_SCALAR_TYPE: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ABI_SCALAR_TYPE: u8 = 9;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ABI_SCALAR_TYPE: [AbiScalarType; 10] = [
  AbiScalarType::I8,
  AbiScalarType::U8,
  AbiScalarType::I16,
  AbiScalarType::U16,
  AbiScalarType::I32,
  AbiScalarType::U32,
  AbiScalarType::I64,
  AbiScalarType::U64,
  AbiScalarType::F32,
  AbiScalarType::F64,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct AbiScalarType(pub u8);
#[allow(non_upper_case_globals)]
impl AbiScalarType {
  pub const I8: Self = Self(0);
  pub const U8: Self = Self(1);
  pub const I16: Self = Self(2);
  pub const U16: Self = Self(3);
  pub const I32: Self = Self(4);
  pub const U32: Self = Self(5);
  pub const I64: Self = Self(6);
  pub const U64: Self = Self(7);
  pub const F32: Self = Self(8);
  pub const F64: Self = Self(9);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 9;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::I8,
    Self::U8,
    Self::I16,
    Self::U16,
    Self::I32,
    Self::U32,
    Self::I64,
    Self::U64,
    Self::F32,
    Self::F64,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::I8 => Some("I8"),
      Self::U8 => Some("U8"),
      Self::I16 => Some("I16"),
      Self::U16 => Some("U16"),
      Self::I32 => Some("I32"),
      Self::U32 => Some("U32"),
      Self::I64 => Some("I64"),
      Self::U64 => Some("U64"),
      Self::F32 => Some("F32"),
      Self::F64 => Some("F64"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for AbiScalarType {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for AbiScalarType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for AbiScalarType {
    type Output = AbiScalarType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for AbiScalarType {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for AbiScalarType {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for AbiScalarType {}
