// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum AbiSignatureOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct AbiSignature<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for AbiSignature<'a> {
  type Inner = AbiSignature<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> AbiSignature<'a> {
  pub const VT_PARAMS: ::flatbuffers::VOffsetT = 4;
  pub const VT_RESULTS: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    AbiSignature { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args AbiSignatureArgs<'args>
  ) -> ::flatbuffers::WIPOffset<AbiSignature<'bldr>> {
    let mut builder = AbiSignatureBuilder::new(_fbb);
    if let Some(x) = args.results { builder.add_results(x); }
    if let Some(x) = args.params { builder.add_params(x); }
    builder.finish()
  }


  #[inline]
  pub fn params(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<AbiParam<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<AbiParam>>>>(AbiSignature::VT_PARAMS, None)}
  }
  #[inline]
  pub fn results(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<AbiParam<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<AbiParam>>>>(AbiSignature::VT_RESULTS, None)}
  }
}

impl ::flatbuffers::Verifiable for AbiSignature<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<AbiParam>>>>("params", Self::VT_PARAMS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<AbiParam>>>>("results", Self::VT_RESULTS, false)?
     .finish();
    Ok(())
  }
}
pub struct AbiSignatureArgs<'a> {
    pub params: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<AbiParam<'a>>>>>,
    pub results: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<AbiParam<'a>>>>>,
}
impl<'a> Default for AbiSignatureArgs<'a> {
  #[inline]
  fn default() -> Self {
    AbiSignatureArgs {
      params: None,
      results: None,
    }
  }
}

pub struct AbiSignatureBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> AbiSignatureBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_params(&mut self, params: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<AbiParam<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(AbiSignature::VT_PARAMS, params);
  }
  #[inline]
  pub fn add_results(&mut self, results: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<AbiParam<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(AbiSignature::VT_RESULTS, results);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> AbiSignatureBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    AbiSignatureBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<AbiSignature<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for AbiSignature<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("AbiSignature");
      ds.field("params", &self.params());
      ds.field("results", &self.results());
      ds.finish()
  }
}
