// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum ChannelReadResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ChannelReadResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ChannelReadResponse<'a> {
  type Inner = ChannelReadResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ChannelReadResponse<'a> {
  pub const VT_FRAME: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ChannelReadResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ChannelReadResponseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ChannelReadResponse<'bldr>> {
    let mut builder = ChannelReadResponseBuilder::new(_fbb);
    if let Some(x) = args.frame { builder.add_frame(x); }
    builder.finish()
  }


  #[inline]
  pub fn frame(&self) -> Option<IoFrame<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<IoFrame>>(ChannelReadResponse::VT_FRAME, None)}
  }
}

impl ::flatbuffers::Verifiable for ChannelReadResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<IoFrame>>("frame", Self::VT_FRAME, false)?
     .finish();
    Ok(())
  }
}
pub struct ChannelReadResponseArgs<'a> {
    pub frame: Option<::flatbuffers::WIPOffset<IoFrame<'a>>>,
}
impl<'a> Default for ChannelReadResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    ChannelReadResponseArgs {
      frame: None,
    }
  }
}

pub struct ChannelReadResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ChannelReadResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_frame(&mut self, frame: ::flatbuffers::WIPOffset<IoFrame<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<IoFrame>>(ChannelReadResponse::VT_FRAME, frame);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ChannelReadResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ChannelReadResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ChannelReadResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ChannelReadResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ChannelReadResponse");
      ds.field("frame", &self.frame());
      ds.finish()
  }
}
