// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum ChannelCreateRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ChannelCreateRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ChannelCreateRequest<'a> {
  type Inner = ChannelCreateRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ChannelCreateRequest<'a> {
  pub const VT_CAPACITY: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ChannelCreateRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ChannelCreateRequestArgs
  ) -> ::flatbuffers::WIPOffset<ChannelCreateRequest<'bldr>> {
    let mut builder = ChannelCreateRequestBuilder::new(_fbb);
    builder.add_capacity(args.capacity);
    builder.finish()
  }


  #[inline]
  pub fn capacity(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ChannelCreateRequest::VT_CAPACITY, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ChannelCreateRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("capacity", Self::VT_CAPACITY, false)?
     .finish();
    Ok(())
  }
}
pub struct ChannelCreateRequestArgs {
    pub capacity: u32,
}
impl<'a> Default for ChannelCreateRequestArgs {
  #[inline]
  fn default() -> Self {
    ChannelCreateRequestArgs {
      capacity: 0,
    }
  }
}

pub struct ChannelCreateRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ChannelCreateRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_capacity(&mut self, capacity: u32) {
    self.fbb_.push_slot::<u32>(ChannelCreateRequest::VT_CAPACITY, capacity, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ChannelCreateRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ChannelCreateRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ChannelCreateRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ChannelCreateRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ChannelCreateRequest");
      ds.field("capacity", &self.capacity());
      ds.finish()
  }
}
