// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum ChannelWriteResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ChannelWriteResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ChannelWriteResponse<'a> {
  type Inner = ChannelWriteResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ChannelWriteResponse<'a> {
  pub const VT_LEN: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ChannelWriteResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ChannelWriteResponseArgs
  ) -> ::flatbuffers::WIPOffset<ChannelWriteResponse<'bldr>> {
    let mut builder = ChannelWriteResponseBuilder::new(_fbb);
    builder.add_len(args.len);
    builder.finish()
  }


  #[inline]
  pub fn len(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ChannelWriteResponse::VT_LEN, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ChannelWriteResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("len", Self::VT_LEN, false)?
     .finish();
    Ok(())
  }
}
pub struct ChannelWriteResponseArgs {
    pub len: u32,
}
impl<'a> Default for ChannelWriteResponseArgs {
  #[inline]
  fn default() -> Self {
    ChannelWriteResponseArgs {
      len: 0,
    }
  }
}

pub struct ChannelWriteResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ChannelWriteResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_len(&mut self, len: u32) {
    self.fbb_.push_slot::<u32>(ChannelWriteResponse::VT_LEN, len, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ChannelWriteResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ChannelWriteResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ChannelWriteResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ChannelWriteResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ChannelWriteResponse");
      ds.field("len", &self.len());
      ds.finish()
  }
}
