// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum ChannelRefOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ChannelRef<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ChannelRef<'a> {
  type Inner = ChannelRef<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ChannelRef<'a> {
  pub const VT_KIND: ::flatbuffers::VOffsetT = 4;
  pub const VT_HANDLE: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ChannelRef { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ChannelRefArgs
  ) -> ::flatbuffers::WIPOffset<ChannelRef<'bldr>> {
    let mut builder = ChannelRefBuilder::new(_fbb);
    builder.add_handle(args.handle);
    builder.add_kind(args.kind);
    builder.finish()
  }


  #[inline]
  pub fn kind(&self) -> ChannelRefKind {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ChannelRefKind>(ChannelRef::VT_KIND, Some(ChannelRefKind::Strong)).unwrap()}
  }
  #[inline]
  pub fn handle(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ChannelRef::VT_HANDLE, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ChannelRef<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<ChannelRefKind>("kind", Self::VT_KIND, false)?
     .visit_field::<u64>("handle", Self::VT_HANDLE, false)?
     .finish();
    Ok(())
  }
}
pub struct ChannelRefArgs {
    pub kind: ChannelRefKind,
    pub handle: u64,
}
impl<'a> Default for ChannelRefArgs {
  #[inline]
  fn default() -> Self {
    ChannelRefArgs {
      kind: ChannelRefKind::Strong,
      handle: 0,
    }
  }
}

pub struct ChannelRefBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ChannelRefBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_kind(&mut self, kind: ChannelRefKind) {
    self.fbb_.push_slot::<ChannelRefKind>(ChannelRef::VT_KIND, kind, ChannelRefKind::Strong);
  }
  #[inline]
  pub fn add_handle(&mut self, handle: u64) {
    self.fbb_.push_slot::<u64>(ChannelRef::VT_HANDLE, handle, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ChannelRefBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ChannelRefBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ChannelRef<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ChannelRef<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ChannelRef");
      ds.field("kind", &self.kind());
      ds.field("handle", &self.handle());
      ds.finish()
  }
}
