// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum EntrypointArgOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EntrypointArg<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for EntrypointArg<'a> {
  type Inner = EntrypointArg<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> EntrypointArg<'a> {
  pub const VT_KIND: ::flatbuffers::VOffsetT = 4;
  pub const VT_SCALAR: ::flatbuffers::VOffsetT = 6;
  pub const VT_BUFFER: ::flatbuffers::VOffsetT = 8;
  pub const VT_RESOURCE: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    EntrypointArg { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EntrypointArgArgs<'args>
  ) -> ::flatbuffers::WIPOffset<EntrypointArg<'bldr>> {
    let mut builder = EntrypointArgBuilder::new(_fbb);
    builder.add_resource(args.resource);
    if let Some(x) = args.buffer { builder.add_buffer(x); }
    if let Some(x) = args.scalar { builder.add_scalar(x); }
    builder.add_kind(args.kind);
    builder.finish()
  }


  #[inline]
  pub fn kind(&self) -> EntrypointArgKind {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<EntrypointArgKind>(EntrypointArg::VT_KIND, Some(EntrypointArgKind::Scalar)).unwrap()}
  }
  #[inline]
  pub fn scalar(&self) -> Option<ScalarValue<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ScalarValue>>(EntrypointArg::VT_SCALAR, None)}
  }
  #[inline]
  pub fn buffer(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(EntrypointArg::VT_BUFFER, None)}
  }
  #[inline]
  pub fn resource(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(EntrypointArg::VT_RESOURCE, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for EntrypointArg<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<EntrypointArgKind>("kind", Self::VT_KIND, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ScalarValue>>("scalar", Self::VT_SCALAR, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("buffer", Self::VT_BUFFER, false)?
     .visit_field::<u64>("resource", Self::VT_RESOURCE, false)?
     .finish();
    Ok(())
  }
}
pub struct EntrypointArgArgs<'a> {
    pub kind: EntrypointArgKind,
    pub scalar: Option<::flatbuffers::WIPOffset<ScalarValue<'a>>>,
    pub buffer: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub resource: u64,
}
impl<'a> Default for EntrypointArgArgs<'a> {
  #[inline]
  fn default() -> Self {
    EntrypointArgArgs {
      kind: EntrypointArgKind::Scalar,
      scalar: None,
      buffer: None,
      resource: 0,
    }
  }
}

pub struct EntrypointArgBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EntrypointArgBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_kind(&mut self, kind: EntrypointArgKind) {
    self.fbb_.push_slot::<EntrypointArgKind>(EntrypointArg::VT_KIND, kind, EntrypointArgKind::Scalar);
  }
  #[inline]
  pub fn add_scalar(&mut self, scalar: ::flatbuffers::WIPOffset<ScalarValue<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ScalarValue>>(EntrypointArg::VT_SCALAR, scalar);
  }
  #[inline]
  pub fn add_buffer(&mut self, buffer: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EntrypointArg::VT_BUFFER, buffer);
  }
  #[inline]
  pub fn add_resource(&mut self, resource: u64) {
    self.fbb_.push_slot::<u64>(EntrypointArg::VT_RESOURCE, resource, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> EntrypointArgBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EntrypointArgBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<EntrypointArg<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for EntrypointArg<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("EntrypointArg");
      ds.field("kind", &self.kind());
      ds.field("scalar", &self.scalar());
      ds.field("buffer", &self.buffer());
      ds.field("resource", &self.resource());
      ds.finish()
  }
}
