// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum ProcessStartResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ProcessStartResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ProcessStartResponse<'a> {
  type Inner = ProcessStartResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ProcessStartResponse<'a> {
  pub const VT_HANDLE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ProcessStartResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ProcessStartResponseArgs
  ) -> ::flatbuffers::WIPOffset<ProcessStartResponse<'bldr>> {
    let mut builder = ProcessStartResponseBuilder::new(_fbb);
    builder.add_handle(args.handle);
    builder.finish()
  }


  #[inline]
  pub fn handle(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ProcessStartResponse::VT_HANDLE, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ProcessStartResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("handle", Self::VT_HANDLE, false)?
     .finish();
    Ok(())
  }
}
pub struct ProcessStartResponseArgs {
    pub handle: u64,
}
impl<'a> Default for ProcessStartResponseArgs {
  #[inline]
  fn default() -> Self {
    ProcessStartResponseArgs {
      handle: 0,
    }
  }
}

pub struct ProcessStartResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ProcessStartResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_handle(&mut self, handle: u64) {
    self.fbb_.push_slot::<u64>(ProcessStartResponse::VT_HANDLE, handle, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ProcessStartResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ProcessStartResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ProcessStartResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ProcessStartResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ProcessStartResponse");
      ds.field("handle", &self.handle());
      ds.finish()
  }
}
