// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_REMOTE_CLIENT_PAYLOAD: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_REMOTE_CLIENT_PAYLOAD: u8 = 14;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_REMOTE_CLIENT_PAYLOAD: [RemoteClientPayload; 15] = [
  RemoteClientPayload::NONE,
  RemoteClientPayload::ChannelCreateRequest,
  RemoteClientPayload::ChannelDeleteRequest,
  RemoteClientPayload::SubscribeRequest,
  RemoteClientPayload::PublishRequest,
  RemoteClientPayload::ProcessStartRequest,
  RemoteClientPayload::ProcessStopRequest,
  RemoteClientPayload::ProcessLogChannelRequest,
  RemoteClientPayload::ChannelCreateResponse,
  RemoteClientPayload::ChannelReadResponse,
  RemoteClientPayload::ChannelWriteResponse,
  RemoteClientPayload::ProcessStartResponse,
  RemoteClientPayload::ProcessLogChannelResponse,
  RemoteClientPayload::OkResponse,
  RemoteClientPayload::ErrorResponse,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct RemoteClientPayload(pub u8);
#[allow(non_upper_case_globals)]
impl RemoteClientPayload {
  pub const NONE: Self = Self(0);
  pub const ChannelCreateRequest: Self = Self(1);
  pub const ChannelDeleteRequest: Self = Self(2);
  pub const SubscribeRequest: Self = Self(3);
  pub const PublishRequest: Self = Self(4);
  pub const ProcessStartRequest: Self = Self(5);
  pub const ProcessStopRequest: Self = Self(6);
  pub const ProcessLogChannelRequest: Self = Self(7);
  pub const ChannelCreateResponse: Self = Self(8);
  pub const ChannelReadResponse: Self = Self(9);
  pub const ChannelWriteResponse: Self = Self(10);
  pub const ProcessStartResponse: Self = Self(11);
  pub const ProcessLogChannelResponse: Self = Self(12);
  pub const OkResponse: Self = Self(13);
  pub const ErrorResponse: Self = Self(14);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 14;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::ChannelCreateRequest,
    Self::ChannelDeleteRequest,
    Self::SubscribeRequest,
    Self::PublishRequest,
    Self::ProcessStartRequest,
    Self::ProcessStopRequest,
    Self::ProcessLogChannelRequest,
    Self::ChannelCreateResponse,
    Self::ChannelReadResponse,
    Self::ChannelWriteResponse,
    Self::ProcessStartResponse,
    Self::ProcessLogChannelResponse,
    Self::OkResponse,
    Self::ErrorResponse,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::ChannelCreateRequest => Some("ChannelCreateRequest"),
      Self::ChannelDeleteRequest => Some("ChannelDeleteRequest"),
      Self::SubscribeRequest => Some("SubscribeRequest"),
      Self::PublishRequest => Some("PublishRequest"),
      Self::ProcessStartRequest => Some("ProcessStartRequest"),
      Self::ProcessStopRequest => Some("ProcessStopRequest"),
      Self::ProcessLogChannelRequest => Some("ProcessLogChannelRequest"),
      Self::ChannelCreateResponse => Some("ChannelCreateResponse"),
      Self::ChannelReadResponse => Some("ChannelReadResponse"),
      Self::ChannelWriteResponse => Some("ChannelWriteResponse"),
      Self::ProcessStartResponse => Some("ProcessStartResponse"),
      Self::ProcessLogChannelResponse => Some("ProcessLogChannelResponse"),
      Self::OkResponse => Some("OkResponse"),
      Self::ErrorResponse => Some("ErrorResponse"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for RemoteClientPayload {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for RemoteClientPayload {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for RemoteClientPayload {
    type Output = RemoteClientPayload;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for RemoteClientPayload {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for RemoteClientPayload {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for RemoteClientPayload {}
pub struct RemoteClientPayloadUnionTableOffset {}

