// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum SubscribeRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SubscribeRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SubscribeRequest<'a> {
  type Inner = SubscribeRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SubscribeRequest<'a> {
  pub const VT_TARGET: ::flatbuffers::VOffsetT = 4;
  pub const VT_CHUNK_SIZE: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SubscribeRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SubscribeRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<SubscribeRequest<'bldr>> {
    let mut builder = SubscribeRequestBuilder::new(_fbb);
    builder.add_chunk_size(args.chunk_size);
    if let Some(x) = args.target { builder.add_target(x); }
    builder.finish()
  }


  #[inline]
  pub fn target(&self) -> Option<ChannelRef<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ChannelRef>>(SubscribeRequest::VT_TARGET, None)}
  }
  #[inline]
  pub fn chunk_size(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(SubscribeRequest::VT_CHUNK_SIZE, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for SubscribeRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ChannelRef>>("target", Self::VT_TARGET, false)?
     .visit_field::<u32>("chunk_size", Self::VT_CHUNK_SIZE, false)?
     .finish();
    Ok(())
  }
}
pub struct SubscribeRequestArgs<'a> {
    pub target: Option<::flatbuffers::WIPOffset<ChannelRef<'a>>>,
    pub chunk_size: u32,
}
impl<'a> Default for SubscribeRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    SubscribeRequestArgs {
      target: None,
      chunk_size: 0,
    }
  }
}

pub struct SubscribeRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SubscribeRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_target(&mut self, target: ::flatbuffers::WIPOffset<ChannelRef<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ChannelRef>>(SubscribeRequest::VT_TARGET, target);
  }
  #[inline]
  pub fn add_chunk_size(&mut self, chunk_size: u32) {
    self.fbb_.push_slot::<u32>(SubscribeRequest::VT_CHUNK_SIZE, chunk_size, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SubscribeRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SubscribeRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SubscribeRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SubscribeRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SubscribeRequest");
      ds.field("target", &self.target());
      ds.field("chunk_size", &self.chunk_size());
      ds.finish()
  }
}
