// Automatically generated by build.rs. Do not modify manually.
// Combined module tree for remote-client Flatbuffers namespaces.
pub mod remote_client {
  use super::*;
  pub mod protocol {
    use super::*;
    mod abi_param_generated;
    pub use self::abi_param_generated::*;
    mod abi_param_kind_generated;
    pub use self::abi_param_kind_generated::*;
    mod abi_scalar_type_generated;
    pub use self::abi_scalar_type_generated::*;
    mod abi_signature_generated;
    pub use self::abi_signature_generated::*;
    mod capability_generated;
    pub use self::capability_generated::*;
    mod channel_create_request_generated;
    pub use self::channel_create_request_generated::*;
    mod channel_create_response_generated;
    pub use self::channel_create_response_generated::*;
    mod channel_delete_request_generated;
    pub use self::channel_delete_request_generated::*;
    mod channel_read_response_generated;
    pub use self::channel_read_response_generated::*;
    mod channel_ref_generated;
    pub use self::channel_ref_generated::*;
    mod channel_ref_kind_generated;
    pub use self::channel_ref_kind_generated::*;
    mod channel_write_response_generated;
    pub use self::channel_write_response_generated::*;
    mod entrypoint_arg_generated;
    pub use self::entrypoint_arg_generated::*;
    mod entrypoint_arg_kind_generated;
    pub use self::entrypoint_arg_kind_generated::*;
    mod error_response_generated;
    pub use self::error_response_generated::*;
    mod io_frame_generated;
    pub use self::io_frame_generated::*;
    mod ok_response_generated;
    pub use self::ok_response_generated::*;
    mod process_log_channel_request_generated;
    pub use self::process_log_channel_request_generated::*;
    mod process_log_channel_response_generated;
    pub use self::process_log_channel_response_generated::*;
    mod process_start_request_generated;
    pub use self::process_start_request_generated::*;
    mod process_start_response_generated;
    pub use self::process_start_response_generated::*;
    mod process_stop_request_generated;
    pub use self::process_stop_request_generated::*;
    mod publish_request_generated;
    pub use self::publish_request_generated::*;
    mod remote_client_message_generated;
    pub use self::remote_client_message_generated::*;
    mod remote_client_payload_generated;
    pub use self::remote_client_payload_generated::*;
    mod scalar_value_generated;
    pub use self::scalar_value_generated::*;
    mod subscribe_request_generated;
    pub use self::subscribe_request_generated::*;
  }
}
